export enum BoardTypes {
  LOAD_DATA = "BOARD/LOAD_DATA",
  COLUMN_NAME_CHANGE = "BOARD/COLUMN_NAME_CHANGE",
  TOGGLE_ADD_CARD_FIELD = "BOARD/TOGGLE_ADD_CARD_FIELD",
  PUSH_NEW_CARD = "BOARD/PUSH_NEW_CARD",
  CARD_DESCRIPTION_CHANGE = "BOARD/CARD_DESCRIPTION_CHANGE",
  CARD_NAME_CHANGE = "BOARD/CARD_NAME_CHANGE",
  ADD_NEW_COMENT = "BOARD/ADD_NEW_COMENT",
  COMMENT_EDIT_SAVE = "BOARD/COMMENT_EDIT_SAVE",
  COMMENT_Delete = "BOARD/COMMENT_Delete",
  DELETE_CARD = "BOARD/DELETE_CARD",
}

export default BoardTypes;
